### ISSUE TITLE
Markdown fails rendering empty code block

### ISSUE THREAD

**Issue by fennovj** [jsvine/notebookjs#20]
Hello,

I just installed this application for my team, it seems to work great so far! However, I found an issue with rendering of one of our jupyter notebooks, specifically the markdown.

A minimal reproduction of the markdown in question is:

````
# Test

```
```

```
**codeblockhere**
```
````

This code works fine in jupyter: it just shows the title, and then a single (the second) code block, and doesn't show the empty code block. 

However, when I test a jupyter notebook containing this markdown on https://jsvine.github.io/nbpreview/ , it seems like the empty code block is not ended properly, and the `**codeblockhere**` segment is rendered as if it was markdown text.

I made sure this was not a marked issue, and as far as I can see, when I just use marked directly, it renders this markdown fine with no issues.

**Comment by jsvine** [comment]
Thanks for flagging!

**Comment by jsvine** [comment]
This seems to have been an issue w/ `nbpreview` using a very old version of `marked`. The problem you've observed appears to have been fixed in `marked` v0.3.5. (Compare the [output of this](https://marked.js.org/demo/?text=%23%20Test%0A%0A%60%60%60%0A%60%60%60%0A%0A%60%60%60%0A**codeblockhere**%0A%60%60%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) when toggling between v0.3.4 and v0.3.5.)

https://github.com/jsvine/nbpreview/commit/c54381bdf2199b57a46c6c2598447cf3e4f90d3a fixes this for `nbpreview` by upgrading `marked` to v0.6.1. 

For your projects, do you still encounter a problem even after upgrading `marked`? If so, don't hesitate to reopen this issue. Thanks!
