### ISSUE TITLE
Using it with Vue.JS

### ISSUE THREAD

**Issue by tbhaxor** [jsvine/notebookjs#26]
I want to use this in Vue.JS. Any example?

**Comment by jsvine** [comment]
If you were having getting `Critical dependency the request of a dependency is an expression` errors, then I believe this has been fixed in https://github.com/jsvine/notebookjs/commit/f3473998ad816d83451fd41b05c5016339c09a21 (see https://github.com/jsvine/notebookjs/issues/27 for more discussion).

Or were you just looking for someone to demonstrate how to integrate `notebookjs` with Vue.js more generally?
